version: '3.8'

services:
  db:
    image: postgres:15
    container_name: cooking_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cooking_platform
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
      build: .
      container_name: cooking_backend
      volumes:
        - .:/app
        - ./static:/app/static
      ports:
        - "8000:8000"
      restart: on-failure
      environment:
        - DATABASE_URL=postgresql://user:password@db:5432/cooking_platform
      depends_on:
        - db

  frontend:
      build: ../frontend
      container_name: cooking_frontend
      volumes:
        - ../frontend:/app
        - /app/node_modules
      ports:
        - "5173:5173"
      depends_on:
        - backend

volumes:
  postgres_data: